tasks:
  - init: |
      python -m venv todo-app-venv
      source todo-app-venv/bin/activate
      pip install --upgrade pip wheel setuptools
      pip install -r requirements.txt
      python manage.py migrate
  - command: |
      source todo-app-venv/bin/activate
      python manage.py runserver

ports: 
  - port: 8000
    visibility: public
    onOpen: open-preview